baseURL = ''
languageCode = 'en-us'
title = 'Hugo Bible Study'
theme = 'm10c'

# [params.notFound]
#   title       = "Page not Found"
  # description  = "This page was not found"
  # paragraph    = "Nothing to sere here, buddy"
