baseURL = ''
languageCode = 'en-us'
title = 'Hugo Bible Study'
theme = ['hugo-coder']

paginate = 10

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 5
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20